# Generated by Django 2.2 on 2019-09-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='what_learn',
            field=models.CharField(default='', max_length=300, verbose_name='能学到的知识'),
        ),
        migrations.AddField(
            model_name='course',
            name='youneed_know',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
